### ISSUE TITLE
Nowy początek 

### ISSUE THREAD

**Issue by Alek96** [Alek96/WebGamesCentre#1]
Wraz z wiosną, przychodzi słońce, kwiaty i chęć na zmiany na lepsze. Dziś jest nią nauka JS!

**Comment by przemekpjski** [comment]
Dziś chcesz się uczyć JS? Ja mam jutro BD i POBO :(

**Comment by Alek96** [comment]
Ja zacznę od jutra, bo dzisiaj też mam jeszcze sporo do nauki :/

**Comment by przemekpjski** [comment]
Tylko ktoś musi jeszcze ogarniać serwer w C++ (boost) ;)
