### ISSUE TITLE
Need for env customization in PocoDir.py config file

### ISSUE THREAD

**Issue by przemekpjski** [Alek96/WebGamesCentre#5]
Modifying the exported env object would give users much more possibilities regarding setting-up their build environment.

One could want to include his own PATH environment variable, enabling himself to build the project successfully when using 'non-standard' compiler/linker/C++ libraries locations, as stated here: [SCons FAQ](http://scons.org/faq.html#Why_doesn.27t_SCons_find_my_compiler.2BAC8-linker.2BAC8-etc..3F_I_can_execute_it_just_fine_from_the_command_line.).

This feature would make people's lives (including mine :P ) much easier, not having to modify the main SConstruct.py file each time to build the project.

If this feature will be introduced, I suggest we change the name of this config file to something like 'buildConfig.py' which speaks for more configuration options.

**Comment by Alek96** [comment]
There is no need to modify the SConstruct.py file to modify the exported env object. I thought that if someone wanted to do it, he/she would modify it in the "PocoDir.py" file.

**Comment by przemekpjski** [comment]
Right. It is already possible.
Must have been tired when working on that. Edited wrong file :/ My bad.
